# Generated by Django 4.2.27 on 2026-01-15 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_id', models.CharField(max_length=5)),
                ('item_name', models.CharField(max_length=50)),
                ('item_price', models.FloatField(max_length=7)),
            ],
        ),
    ]
