# Generated by Django 4.2.27 on 2026-01-16 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0002_item'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=5)),
                ('user_name', models.CharField(max_length=40)),
                ('user_email', models.CharField(max_length=50)),
            ],
        ),
    ]
