# Generated by Django 4.2.27 on 2026-01-14 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.CharField(max_length=5)),
                ('name', models.CharField(max_length=30)),
                ('branch', models.CharField(max_length=50)),
            ],
        ),
    ]
